# InvoicePe - Elon-Style Analysis Options
# "The best lint warning is no lint warning" - Focus on bug prevention over style
# TIER 1: Critical (errors), TIER 2: Performance (warnings), TIER 3: Style (automated)

include: package:flutter_lints/flutter.yaml

analyzer:
  # Treat missing required parameters as errors
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  # Exclude generated files from analysis
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated_plugin_registrant.dart"
    - "lib/generated/**"
    - "build/**"
    - ".dart_tool/**"

  # Enable additional error checking
  errors:
    # Treat these as errors instead of warnings
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error
    dead_code: error
    unused_import: error
    unused_local_variable: error

  # Language features
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # === TIER 1: CRITICAL (Bug Prevention) ===
    # These prevent runtime crashes and security issues
    avoid_dynamic_calls: true
    avoid_type_to_string: true
    close_sinks: true
    hash_and_equals: true
    no_adjacent_strings_in_list: true
    unrelated_type_equality_checks: true

    # === TIER 2: PERFORMANCE (Measurable Impact) ===
    # These have measurable performance benefits
    avoid_function_literals_in_foreach_calls: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    unnecessary_to_list_in_spreads: true

    # === TIER 3: STYLE (Automated via dart format/fix) ===
    # These are handled by automation, not manual fixes
    always_declare_return_types: true
    annotate_overrides: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    curly_braces_in_flow_control_structures: true
    prefer_single_quotes: true
    require_trailing_commas: true
    use_key_in_widget_constructors: true

    # === SUPPRESSED STYLE RULES ===
    # These create noise without preventing bugs
    always_put_required_named_parameters_first: false
    prefer_final_fields: false
    prefer_final_in_for_each: false
    prefer_final_locals: false
    sort_child_properties_last: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: false

    # === DOCUMENTATION RULES ===
    # Suppressed to reduce noise during development
    public_member_api_docs: false
    dangling_library_doc_comments: false
    unintended_html_in_doc_comment: false
