name: invoice_pe_app
description: "InvoicePe - Smart Invoice Management & Payment Platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies (TRD Mandatory Stack)
  # State Management
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^16.0.0

  # Networking
  dio: ^5.7.0

  # Local Storage
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5

  # Data Classes
  dart_mappable: ^4.5.0

  # Animations
  flutter_animate: ^4.5.0

  # Security & Environment
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0

  # Supabase Integration (UPDATED - fixes OTP issues)
  supabase_flutter: ^2.9.1

  # Local Database & Storage (DEFERRED to Phase 2 - version conflict with dart_mappable)
  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1

  # Invoice Features (NEW - Phase 1 additions)
  image_picker: ^1.1.2
  pdf: ^3.11.1
  permission_handler: ^11.3.1

  # PhonePe Payment Integration
  phonepe_payment_sdk: ^2.0.3

  # Enhanced Forms & UX (NEW - Phase 1 additions)
  reactive_forms: ^17.0.1
  form_builder_validators: ^11.0.0
  cached_network_image: ^3.4.1

  # Security & Authentication (NEW - Phase 1 additions)
  local_auth: ^2.3.0
  encrypt: ^5.0.3
  crypto: ^3.0.3

  # Payment Features (NEW - Phase 1 additions)
  mobile_scanner: ^5.0.0  # QR/Barcode scanning (replaces qr_code_scanner)
  logger: ^2.4.0  # For comprehensive logging

  # UI/UX Enhancements
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1

  # Utilities
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation - dart_mappable for Flutter 3.32/Dart 3.8 compatibility
  build_runner: ^2.5.4
  dart_mappable_builder: ^4.5.0

  # Isar Code Generation (DEFERRED to Phase 2 - version conflict with dart_mappable)
  # isar_generator: ^3.1.0

  # Linting
  flutter_lints: ^6.0.0

# Force compatible versions for Flutter 3.32/Dart 3.8
dependency_overrides:
  # Core Dart/Flutter packages
  meta: ^1.17.0
  material_color_utilities: ^0.13.0
  vector_math: ^2.2.0
  characters: ^1.4.1

  # Testing packages
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  test_api: ^0.7.6
  vm_service: ^15.0.2

  # Platform-specific secure storage (safe updates)
  flutter_secure_storage_linux: ^2.0.1
  flutter_secure_storage_macos: ^4.0.0
  flutter_secure_storage_platform_interface: ^2.0.1
  flutter_secure_storage_web: ^2.0.0
  flutter_secure_storage_windows: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - .env

  # Fonts (UX Requirements: Inter/SF Pro)
  # TODO: Add Inter font files to assets/fonts/ directory
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
