name: invoice_pe_app
description: "InvoicePe - Smart Invoice Management & Payment Platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies (TRD Mandatory Stack)
  # State Management
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^16.0.0

  # Networking
  dio: ^5.7.0

  # Local Storage
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5

  # Data Classes
  dart_mappable: ^4.5.0
  
  # Meta annotations
  meta: ^1.17.0

  # Animations
  flutter_animate: ^4.5.0

  # Security & Environment
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0

  # Supabase Integration (UPDATED - fixes OTP issues)
  supabase_flutter: ^2.9.1

  # Local Database & Storage (DEFERRED to Phase 2 - version conflict with dart_mappable)
  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1

  # Invoice Features (NEW - Phase 1 additions)
  image_picker: ^1.1.2
  pdf: ^3.11.1
  permission_handler: ^12.0.1  # Updated for Codemagic compatibility

  # PhonePe Payment Integration (UPGRADED - Latest tech)
  phonepe_payment_sdk: ^3.0.0

  # Enhanced Forms & UX (UPGRADED - Latest tech)
  reactive_forms: ^18.1.1
  form_builder_validators: ^11.0.0
  cached_network_image: ^3.4.1

  # Security & Authentication (NEW - Phase 1 additions)
  local_auth: ^2.3.0
  encrypt: ^5.0.3
  crypto: ^3.0.3

  # Payment Features (UPGRADED - Latest tech)
  mobile_scanner: ^7.0.1  # QR/Barcode scanning (replaces qr_code_scanner)
  logger: ^2.4.0  # For comprehensive logging

  # UI/UX Enhancements
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1

  # Utilities
  cupertino_icons: ^1.0.8
  share_plus: ^10.0.0  # For sharing PDFs

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Revolutionary Testing Stack 2025 (UPGRADED - Latest tech)
  patrol: ^3.11.0                   # Revolutionary integration testing
  mocktail: ^1.0.4                  # Type-safe mocking
  bloc_test: ^10.0.0                # State management testing (UPGRADED)
  very_good_analysis: ^9.0.0        # Modern lint rules (UPGRADED)
  fake_async: ^1.3.1                # Time manipulation for tests

  # Code Generation - dart_mappable for Flutter 3.32/Dart 3.8 compatibility
  build_runner: ^2.5.4
  dart_mappable_builder: ^4.5.0
  
  # App Icon Generation
  flutter_launcher_icons: ^0.13.1

  # Isar Code Generation (DEFERRED to Phase 2 - version conflict with dart_mappable)
  # isar_generator: ^3.1.0

  # Linting (Updated to very_good_analysis)
  # flutter_lints: ^6.0.0  # Replaced by very_good_analysis

  # Splash screen generation
  flutter_native_splash: ^2.4.1

# ELON-STYLE DEPENDENCY OVERRIDES (Research-based fixes for Codemagic)
# Eliminates "X packages have newer versions incompatible" errors
dependency_overrides:
  # Core Dart/Flutter packages (keep only essential)
  meta: ^1.17.0
  material_color_utilities: ^0.13.0
  vector_math: ^2.2.0

  # CRITICAL: js package discontinued - override to prevent CI failures
  # Source: https://dart.dev/go/package-discontinue
  js: ^0.6.7

  # Testing framework compatibility (prevents version conflicts)
  leak_tracker: ^10.0.9
  test_api: ^0.7.4

  # Flutter Secure Storage platform compatibility (ELON FIX)
  # Prevents platform-specific build failures in CI
  flutter_secure_storage_platform_interface: ^1.1.2
  flutter_secure_storage_linux: ^1.2.3
  flutter_secure_storage_macos: ^3.1.3
  flutter_secure_storage_web: ^1.2.1
  flutter_secure_storage_windows: ^3.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    # NOTE: Never include .env in assets - it exposes secrets

  # Fonts (User Specification: Inter font family)
  # TODO: Add Inter font files to assets/fonts/ directory
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  # Android Adaptive Icons
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_square.png"
  # iOS
  remove_alpha_ios: true
  # Web
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#0D3B66"
  # Windows
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 256
  # macOS
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
