name: Flutter CI - InvoicePe

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.6'
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
        cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
    
    # Cache pub dependencies
    - name: Cache pub dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          .dart_tool
          .packages
          pubspec.lock
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pub-
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Generate code
      run: dart run build_runner build --delete-conflicting-outputs
    
    - name: Apply automated fixes
      run: dart fix --apply
    
    - name: Format code
      run: dart format --set-exit-if-changed .
    
    - name: Analyze code
      run: flutter analyze --no-fatal-infos
    
    - name: Run tests
      run: flutter test
    
    - name: Check for unused imports
      run: |
        if flutter analyze | grep -q "unused_import"; then
          echo "❌ Found unused imports!"
          exit 1
        fi
        echo "✅ No unused imports found"
  
  build-android:
    needs: analyze-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.6'
        channel: 'stable'
        cache: true
    
    - name: Cache pub dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          .dart_tool
          .packages
          pubspec.lock
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pub-
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Generate code
      run: dart run build_runner build --delete-conflicting-outputs
    
    - name: Build APK
      run: flutter build apk --debug
    
    - name: Build App Bundle
      run: flutter build appbundle --debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: build/app/outputs/flutter-apk/app-debug.apk
    
    - name: Upload App Bundle
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.aab
        path: build/app/outputs/bundle/debug/app-debug.aab
